components:
  schemas:
    CoasterCreateDTO:
      properties:
        dl_trasy:
          description: "D\u0142ugo\u015B\u0107 trasy w metrach"
          example: 800
          minimum: 1
          type: integer
        godziny_do:
          example: '18:00'
          format: time
          type: string
        godziny_od:
          example: 08:00
          format: time
          type: string
        id:
          example: A1
          type: string
        liczba_klientow:
          example: 200
          minimum: 0
          type: integer
        liczba_personelu:
          example: 10
          minimum: 0
          type: integer
      required:
      - id
      - liczba_personelu
      - liczba_klientow
      - dl_trasy
      - godziny_od
      - godziny_do
      type: object
    CoasterUpdateDTO:
      properties:
        godziny_do:
          example: '17:00'
          format: time
          type: string
        godziny_od:
          example: 09:00
          format: time
          type: string
        liczba_klientow:
          example: 300
          type: integer
        liczba_personelu:
          example: 12
          type: integer
      required:
      - liczba_personelu
      - liczba_klientow
      - godziny_od
      - godziny_do
      type: object
    WagonCreateDTO:
      properties:
        ilosc_miejsc:
          example: 32
          type: integer
        predkosc_wagonu:
          example: 1.2
          format: float
          type: number
        wagon_id:
          example: W1
          type: string
      required:
      - wagon_id
      - ilosc_miejsc
      - predkosc_wagonu
      type: object
info:
  description: "API do zarz\u0105dzania kolejkami g\xF3rskimi, wagonami, personelem\
    \ i zdolno\u015Bciami obs\u0142ugi klient\xF3w.\n"
  title: "System Kolejek G\xF3rskich \u2013 API"
  version: 1.0.0
openapi: 3.0.3
paths:
  /api/coasters:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoasterCreateDTO'
        required: true
      responses:
        '201':
          description: Kolejka dodana
        '422':
          description: "B\u0142\u0105d walidacji"
      summary: "Dodaj now\u0105 kolejk\u0119 g\xF3rsk\u0105"
  /api/coasters/{coasterId}:
    put:
      parameters:
      - in: path
        name: coasterId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CoasterUpdateDTO'
        required: true
      responses:
        '200':
          description: Zaktualizowano
        '404':
          description: Kolejka nie znaleziona
        '422':
          description: "B\u0142\u0105d walidacji"
      summary: "Zmie\u0144 dane kolejki g\xF3rskiej"
  /api/coasters/{coasterId}/diagnostic:
    get:
      operationId: diagnoseCoaster
      parameters:
      - description: "ID kolejki g\xF3rskiej"
        in: path
        name: coasterId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  capacityStatus:
                    properties:
                      excessClients:
                        type: integer
                      expectedClients:
                        type: integer
                      maxPossibleClients:
                        type: integer
                      missingClients:
                        type: integer
                      sufficient:
                        type: boolean
                    type: object
                  coasterId:
                    type: string
                  isProblem:
                    type: boolean
                  personnelStatus:
                    properties:
                      available:
                        type: integer
                      excess:
                        type: integer
                      missing:
                        type: integer
                      required:
                        type: integer
                      sufficient:
                        type: boolean
                    type: object
                  summary:
                    type: string
                type: object
          description: Raport diagnostyczny kolejki
        '404':
          description: "Kolejka nie zosta\u0142a znaleziona"
      summary: "Analiza diagnostyczna kolejki g\xF3rskiej"
      tags:
      - Coasters
  /api/coasters/{coasterId}/wagons:
    post:
      parameters:
      - in: path
        name: coasterId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WagonCreateDTO'
        required: true
      responses:
        '201':
          description: Wagon dodany
        '404':
          description: Kolejka nie znaleziona
        '422':
          description: "B\u0142\u0105d walidacji"
      summary: Dodaj nowy wagon do kolejki
  /api/coasters/{coasterId}/wagons/{wagonId}:
    delete:
      parameters:
      - in: path
        name: coasterId
        required: true
        schema:
          type: string
      - in: path
        name: wagonId
        required: true
        schema:
          type: string
      responses:
        '204':
          description: "Usuni\u0119to"
        '404':
          description: Kolejka lub wagon nie istnieje
      summary: "Usu\u0144 wagon z kolejki"
servers:
- url: http://localhost:8080
